local eid = GetUpdatedEntityID()
local x, y = EntityGetTransform( eid )
local gec = EntityGetFirstComponent(eid, "GameEffectComponent")
local caster = ComponentGetValue2( gec, "mCaster" )
local root = EntityGetRootEntity(eid)
local dmc = EntityGetFirstComponent( root, "DamageModelComponent" )
local hp = ComponentGetValue2( dmc, "hp" )
ComponentSetValue2( dmc, "hp", 0.01 )
EntityInflictDamage( root, hp * 100, "DAMAGE_DROWNING", "Golden Ego's Midas", "NONE", 0, 0, caster, x, y, 0 )